# configuration alsa loop for svxlink <-> SvxBridge

pcm_slave.hw_Loopback_1_1 {
	pcm "hw:Loopback,0,1"
	format S16_LE
	channels 2
	rate 48000
}

pcm.plug_Loopback_1_1 {
	type plug
	slave hw_Loopback_1_1
	ttable {
		# Copy input 0 channel to output channel 0 and 1
		0.0 = 1
		0.1 = 1
	}
}
pcm_slave.hw_Loopback_1_2 {
	pcm "hw:Loopback,1,2"
	format S16_LE
	channels 2
	rate 48000
}

pcm.plug_Loopback_1_2 {
	type plug
	slave hw_Loopback_1_2
	ttable {
		# Copy input 0 channel to output channel 0 and 1
		0.0 = 1
		0.1 = 1
	}
}